In [18]:
import numpy as np
from numpy import random

# Excercise 1

### 1. Create a matrix from a list which has 4 rows and 3 columns

In [12]:
my_list = [[1,2,3],
           [2,3,4],
           [1,2,1],
           [1,2,2]]

np.array(my_list)

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 1],
       [1, 2, 2]])

### 2. Create matrix 2x3

In [13]:
np.array([[2,7,12,0],
          [3,9,3,4],
          [4,0,1,3]]).shape

(3, 4)

### 3. Create a 2D matrix with size of 10

In [14]:
np.zeros((2,5)).size

10

### 4. Create 3D Matrix of ones which has 2 rows, 3 columns, and 3 depth

In [15]:
np.ones((2,3,3)).shape

(2, 3, 3)

#### 5. Make the following arrays from zeros arrays and with for loops

In [16]:
my_matrix = np.zeros((2,5))

for x in my_matrix:
    print(x+2)

[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]


# Excercise 2

### 1. Generate a 1-D array containing 5 random integers from 0 to 100

In [19]:
random.randint(0, 100, size=5)

array([35, 33, 81, 46, 88])

### 2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

In [20]:
random.randint(0, 100, size=(3,5))

array([[49, 22, 61, 69, 53],
       [25, 92, 41, 61, 37],
       [70, 51,  4, 99, 52]])

### 3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

In [23]:
np.linspace(1.5, 5.5, 30)

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])

# Excercise 3

### 1. create a 3x3 matrix with values ranging from 2 to 10

In [24]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 2. concentenate the following arrays 

In [26]:
x = np.array([[1,2,3], [1,1,1]])
y = np.array([[3,3,1], [1,2,3]])
np.concatenate((x, y), axis = 0)

array([[1, 2, 3],
       [1, 1, 1],
       [3, 3, 1],
       [1, 2, 3]])

# Excercise 4

### 1. create a null vector / 1D array of size 10 and update fifth value to 11.

In [29]:
m = np.arange(10)
m[4] = 11
m

array([ 0,  1,  2,  3, 11,  5,  6,  7,  8,  9])

### 2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [46]:
np.arange(2,8).reshape(2,3).T.shape

(3, 2)

### 3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [53]:
x = np.ones((5,5))
x[1:4, 1:4] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 4. Take a look at the following matrix. Access the [2, 1,1]

In [54]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

z[2,1,1]

2

# Assignment

### 1. Create a 4x4 matrix with values ranging from 0 to 3

In [58]:
random.randint(0, 4, size=(4,4))

array([[1, 0, 3, 1],
       [3, 2, 0, 1],
       [2, 0, 1, 0],
       [0, 2, 1, 2]])

### 2. Create and array with shape of 4x4 and turn it into two arrays along the second axis

In [66]:
np.split(random.randint(0, 4, size=(4,4)), (2, 4), axis=1)

[array([[2, 2],
        [3, 1],
        [3, 3],
        [3, 3]]), array([[0, 1],
        [3, 2],
        [0, 2],
        [3, 3]]), array([], shape=(4, 0), dtype=int64)]